@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJkZW1vQGV4YW1wbGUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3Mzg1MTQ3ODQsImV4cCI6MjA1NDA5MDc4NH0.qTlM8EEojDHHQRFVqL0NNAtzt5axSN3z1cQZulEACUY

###
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "email": "demo@example.com",
    "password": "Demo@P45ssW0rd123"
}

###
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "user123@gmail.com",
    "password": "P4ssWord@123",
    "role": "admin"
}

###
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "email": "user123@gmail.com",
    "password": "P4ssWord@123"
}

###
GET http://localhost:3000/api/user/findAll
Authorization: Bearer {{token}}


###
DELETE http://localhost:3000/api/user/delete/1
Authorization: Bearer {{token}}

###
GET http://localhost:3000/api/user/private/dashboard
Authorization: Bearer {{token}}