@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJmZ3A1NTVAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM3Nzg4NDY1LCJleHAiOjE3Mzc4NzQ4NjV9._wm2LUUTBdpnHivyeqFeppxKywsHkSVRW0lOMjwV1qo

###
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "email": "demo@example.com",
    "password": "Demo@P45ssW0rd123"
}

###
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "user123@gmail.com",
    "password": "P4ssWord@123",
    "role": "admin"
}

###
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "email": "user123@gmail.com",
    "password": "P4ssWord@123"
}

###
GET http://localhost:3000/api/users/findAll
Authorization: Bearer {{token}}


###
DELETE http://localhost:3000/api/users/delete/1
Authorization: Bearer {{token}}

###
GET http://localhost:3000/api/private/dashboard
Authorization: Bearer {{token}}